# Generated by Django 5.2.8 on 2026-07-13 01:21

import admissions.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('mobile', models.CharField(db_index=True, max_length=15, validators=[admissions.validators.validate_mobile_number])),
                ('address', models.TextField()),
                ('dob', models.DateField(validators=[admissions.validators.validate_dob_not_future], verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('qualification', models.CharField(help_text='Highest qualification completed.', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Academic percentage, 0-100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('admission_year', models.PositiveIntegerField(db_index=True, validators=[admissions.validators.validate_admission_year_not_past])),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('FEE_PENDING', 'Fee Pending'), ('ADMITTED', 'Admitted'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=25)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes visible to staff only.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(editable=False, help_text="Automatically set from the selected course's college — not independently editable.", on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='courses.college')),
                ('course', models.ForeignKey(help_text='Course the student is interested in.', on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='courses.course')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='The logged-in student who submitted this enquiry, if any (student accounts are a future phase).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'admission_year'], name='admissions__status_59899d_idx'), models.Index(fields=['is_deleted', 'status'], name='admissions__is_dele_68a4f2_idx'), models.Index(fields=['college', 'status'], name='admissions__college_2d3583_idx')],
            },
        ),
    ]
