# Generated by Django 5.2.8 on 2026-07-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colleges/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='colleges/covers/')),
                ('short_description', models.CharField(blank=True, help_text='One-line summary shown on college cards.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text="Full display name of the course, e.g. 'B.Tech Computer Science'.", max_length=150)),
                ('duration', models.CharField(help_text="Human-readable duration, e.g. '4 Years' or '18 Months'.", max_length=50)),
                ('eligibility', models.CharField(help_text='Minimum eligibility criteria for admission to this course.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive courses are hidden from the public site but preserved for historical enquiries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.college')),
            ],
            options={
                'ordering': ['college__name', 'course_name'],
                'constraints': [models.UniqueConstraint(fields=('college', 'course_name'), name='unique_course_name_per_college')],
            },
        ),
    ]
